### PR TITLE
Add server update instructions

### PR DESCRIPTION
**Pull request by dragonfly8677**
Adds instructions for how to update the game server version for when the game releases an update.

### CODE REVIEW

**Comment by JedMeister** [comment]
Legend! Sorry I missed this earlier (when I replied to your post on the forums). Obviously you were way in front of me! Thanks so much for the improvement to the docs. I'll merge this right now!

**Comment by dragonfly8677** [comment]
Haha, glad I could help. Apparently I messed up the links though, this isn't quite how I imagined it:
{19076644-A390-459F-BC68-69D8A64CCCC9}

I also attempted to add a UI element in `confconsole`, where I wanted to add the ability to update the server. I was thinking it could be nicely added to the "Game server" menu, something like this:

- Select game
- Update game server
- Update game list

However, I think I was too unfamiliar with python, so I couldn't figure out how to see if a game server was installed and if so, which one was installed. And since that short name was needed to update the server, I couldn't make much progress.

**Comment by JedMeister** [comment]
TBH, I missed that url rendering (just looked at the diff and merged).

On face value it looks right, but then I realized that it's actually rst (resturctured text), not markdown. I quite like rst, but TBH I think markdown is a bit friendlier, so I'll look to rewrite that doc in markdown. It won't take long, but I won't get to it today...

Re your idea of an improvement to confconsole, I think it's a great idea. I'm fairly handy with python, but have limited experience with the gameserver itself. Between the doc update you've done and the existing confconsole plugins, it shouldn't be too hard. I think perhaps reusing [this firstboot script](https://github.com/turnkeylinux-apps/gameserver/blob/master/overlay/usr/lib/inithooks/bin/updateGameList.sh) might get us at least part way there?

I'm happy to try to help out if you want to have a crack at it, otherwise I'll try to get to it, but not sure when I'll have time (I've got a huge backlog...).

Perhaps as a first step, you could open a new issue on our [issue tracker](https://github.com/turnkeylinux/tracker/issues/)? You won't be able to add tags, but if you open it, I'll do that when I get a chance.

Thanks again. :grin:

**Comment by dragonfly8677** [comment]
You can find the new issue here:

https://github.com/turnkeylinux/tracker/issues/1990

I'll try to take another look once I've recovered from my fever.

**Comment by JedMeister** [comment]
Hope you feel better soon.

**Pull request merged**
