### PR TITLE
Add ability to update game server from confconsole ui

### PR DESCRIPTION
**Pull request by dragonfly8677**
So I believe this is the solution to https://github.com/turnkeylinux/tracker/issues/1990. No idea how to test it though, frankly it might not even compile, so I was hoping a maintainer would be able to test it out and see if it works as expected.

I'll add documentation once it's working, so please don't merge until it's tested and documentation has been updated.

### CODE REVIEW

**Comment by JedMeister** [comment]
I haven't done any review of the code yet. But to test, just make these same changes on your local gameserver. I.e. something like this:
```
cd /usr/lib/confconsole/plugins.d/Game_Server/
mv update.py update_list.py
wget https://raw.githubusercontent.com/Elyviere/gameserver/refs/heads/master/overlay/usr/lib/confconsole/plugins.d/Game_Server/update_server.py
```
Then run `confconsole`, navigate through the menu and test your new option.

Let me know how you go! :)

**Comment by dragonfly8677** [comment]
That testing procedure was easier than expected, very nice.

Made some small fixes and updated the documentation. This is the new menu (not sure what's up with the colours/contrasts, but that's most likely just my console):

image

**Comment by JedMeister** [comment]
Great work @Elyviere :grin: Thanks for your contribution.

 From a quick glance at this PR it looks good but we'll want a "proper" code review before merging. Hopefully we'll get that done ASAP.

**Review by OnGle — APPROVED** [review]
Looks good to me, no notes. Thanks for the contribution!

**Comment by dragonfly8677** [comment]
Happy to have helped!

**Comment by JedMeister** [comment]
Awesome. :grin:

**Pull request merged**
