### PR TITLE
Utilise check-update and update commands for servers

### PR DESCRIPTION
**Pull request by dragonfly8677**
This is a follow-up to https://github.com/turnkeylinux-apps/gameserver/pull/14.

Updating a server will now first check for available updates using `check-update`, and will then proceed to update the server using the `update` command rather than attempting to reinstall the entire server.

The user is now also prompted at appropriate times and the identified game and versions are now displayed during the update process.

### CODE REVIEW

**Review by OnGle — APPROVED** [review]
Looks good to me, tested with no issues.

**Comment by OnGle** [comment]
@JedMeister when you get back, merge this please

**Comment by OnGle** [comment]
Good catch, I completely missed that :+1:

**Comment by dragonfly8677** [comment]
I noticed it when I used it, just a lucky catch.

**Comment by JedMeister** [comment]
Good catch @Elyviere & thanks for testing @OnGle 

I aim to rebuild the gameserver app to include this (& #14) by the end of this week so should be published by early next week.

Thanks again guys :grin:

**Comment by JedMeister** [comment]
The new v18.1 build - including this - is now available :grin:

**Pull request merged**
